# Generated by Django 6.0.5 on 2026-05-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('min_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
