# Generated by Django 6.0.5 on 2026-05-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_compensationplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_login', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('position_title', models.CharField(blank=True, max_length=200)),
                ('unique_name', models.CharField(blank=True, max_length=200)),
                ('hierarchy', models.CharField(blank=True, max_length=200)),
                ('personal_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('personal_currency', models.CharField(default='INR', max_length=10)),
                ('business_group', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pay_period_type', models.CharField(default='Monthly', max_length=50)),
                ('function_name', models.CharField(blank=True, max_length=100)),
                ('title_category', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('market', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
