# Generated by Django 6.0.5 on 2026-05-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0009_remove_order_customer_name_remove_order_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensationplan',
            name='basis_value',
        ),
        migrations.RemoveField(
            model_name='compensationplan',
            name='level',
        ),
        migrations.RemoveField(
            model_name='compensationplan',
            name='market',
        ),
        migrations.CreateModel(
            name='SCFlatRateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_rate', models.DecimalField(decimal_places=4, help_text='Percentage value. Example: 3.00 = 3%', max_digits=8)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('minimum_sales_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compensation_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc_flat_rate_tables', to='commissions.compensationplan')),
            ],
        ),
        migrations.CreateModel(
            name='SCRateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('to_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for no upper limit', max_digits=15, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=4, help_text='Percentage value. Example: 5.00 = 5%', max_digits=8)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compensation_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc_rate_tables', to='commissions.compensationplan')),
            ],
            options={
                'ordering': ['sequence', 'from_amount'],
            },
        ),
    ]
