# Generated by Django 6.0.5 on 2026-05-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
