# Generated by Django 6.0.5 on 2026-05-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0012_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationplan',
            name='commission_table_type',
            field=models.CharField(choices=[('RATE', 'SC Rate Table'), ('FLAT', 'SC Flat Rate Table')], default='RATE', help_text='Select which commission table type this plan uses.', max_length=10),
        ),
    ]
