# Generated by Django 6.0.5 on 2026-05-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0013_compensationplan_commission_table_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position_name',
            field=models.CharField(max_length=255),
        ),
    ]
