# Generated by Django 6.0.5 on 2026-05-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0015_alter_order_employee_id_alter_order_position_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationplan',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
