# Generated by Django 6.0.5 on 2026-05-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0022_userprofile_position_optional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncentiveRule',
        ),
    ]
