# Generated by Django 6.0.5 on 2026-06-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0032_sc_lookup_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionrulecondition',
            name='field',
            field=models.CharField(choices=[('region', 'Region'), ('product_name', 'Product'), ('service_name', 'Service'), ('distribution', 'Distribution'), ('customer_segment', 'Customer Segment'), ('business_group', 'Business Group'), ('order_status', 'Order Status'), ('currency', 'Currency'), ('position_name', 'Position Name'), ('employee_id', 'Employee ID'), ('sales_amount', 'Sales Amount'), ('territory_code', 'Territory Code'), ('role', 'Role'), ('plan_basis', 'Plan Basis')], max_length=50),
        ),
    ]
