# Generated by Django 6.0.5 on 2026-06-22 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0036_userinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='calculation_scope',
            field=models.CharField(choices=[('order', 'Order'), ('employee_month', 'Employee month')], db_index=True, default='order', max_length=32),
        ),
        migrations.AddField(
            model_name='commission',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='commission',
            name='period_end',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='period_start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='source_order_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='commission',
            name='source_sales_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['organization', 'calculation_scope', 'period_start', 'employee'], name='comm_org_scope_period_idx'),
        ),
    ]
