# Generated by Django 6.0.5 on 2026-07-21 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0042_order_crm_sync_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], db_index=True, default='Draft', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Leave blank for open-ended effectivity.', null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('pay_period_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annual', 'Annual')], default='Monthly', max_length=20)),
                ('plan_basis', models.CharField(choices=[('Product', 'Product'), ('Service', 'Service'), ('Individual', 'Individual'), ('Role', 'Role'), ('Region', 'Region'), ('Customer Segment', 'Customer Segment')], default='Individual', max_length=50)),
                ('commission_table_type', models.CharField(choices=[('RATE', 'SC Rate Table'), ('FLAT', 'SC Flat Rate Table'), ('LOOKUP', 'SC Lookup Table')], default='RATE', max_length=10)),
                ('position_name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('business_group', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['compensation_plan_id', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='PlanVersionQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('quota_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['year', 'month'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='uniq_crm_user_id_per_org',
        ),
        migrations.AlterField(
            model_name='integrationsynclog',
            name='sync_type',
            field=models.CharField(choices=[('users', 'Users pull'), ('orders', 'Orders pull'), ('webhook_users', 'Users webhook'), ('webhook_orders', 'Orders webhook'), ('hubspot_webhook', 'HubSpot webhook'), ('auto', 'Automatic scheduled sync')], db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='commissionplanversion',
            name='compensation_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='commissions.compensationplan'),
        ),
        migrations.AddField(
            model_name='commissionplanversion',
            name='created_from_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='commissions.commissionplanversion'),
        ),
        migrations.AddField(
            model_name='commissionplanversion',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_plan_versions', to='commissions.organization'),
        ),
        migrations.AddField(
            model_name='commissionplanversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_plan_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionplanversion',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_versions', to='commissions.territory'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='plan_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='commissions.commissionplanversion'),
        ),
        migrations.AddField(
            model_name='commission',
            name='plan_version',
            field=models.ForeignKey(blank=True, help_text='Immutable plan version used for this calculation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='commissions.commissionplanversion'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='plan_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='commissions.commissionplanversion'),
        ),
        migrations.AddField(
            model_name='scflatratetable',
            name='plan_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sc_flat_rate_tables', to='commissions.commissionplanversion'),
        ),
        migrations.AddField(
            model_name='sclookuptable',
            name='plan_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sc_lookup_tables', to='commissions.commissionplanversion'),
        ),
        migrations.AddField(
            model_name='scratetable',
            name='plan_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sc_rate_tables', to='commissions.commissionplanversion'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['plan_version', 'period_start'], name='comm_plan_version_period_idx'),
        ),
        migrations.AddField(
            model_name='planversionquota',
            name='plan_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='commissions.commissionplanversion'),
        ),
        migrations.AddIndex(
            model_name='commissionplanversion',
            index=models.Index(fields=['organization', 'status', 'effective_from'], name='cpv_org_status_from_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionplanversion',
            index=models.Index(fields=['compensation_plan', 'status', 'effective_from'], name='cpv_plan_status_from_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionplanversion',
            constraint=models.UniqueConstraint(fields=('compensation_plan', 'version_number'), name='uniq_plan_version_number'),
        ),
        migrations.AddConstraint(
            model_name='commissionplanversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Draft')), fields=('compensation_plan',), name='uniq_one_draft_version_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='commissionplanversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='plan_version_effective_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='planversionquota',
            constraint=models.UniqueConstraint(fields=('plan_version', 'year', 'month'), name='uniq_quota_per_version_month'),
        ),
        migrations.AddConstraint(
            model_name='planversionquota',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='quota_month_valid'),
        ),
    ]
