# Generated by Django 6.0.5 on 2026-07-23 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0053_participant_plan_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='commission',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_to_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('calculated', 'Calculated'), ('manager_approved', 'Manager approved'), ('approved', 'Finance approved'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='calculated', max_length=20),
        ),
        migrations.CreateModel(
            name='CommissionAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('manual', 'Manual Adjustment'), ('bonus', 'Bonus'), ('correction', 'Correction'), ('clawback', 'Clawback')], db_index=True, default='manual', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='commissions.commission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_adjustments', to='commissions.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
