# Generated by Django 6.0.5 on 2026-07-23 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0054_commission_ops_adjustments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externalintegration',
            name='auth_method',
            field=models.CharField(blank=True, choices=[('oauth', 'OAuth 2.0'), ('token', 'Access token'), ('password', 'Username / password')], default='token', max_length=20),
        ),
        migrations.AddField(
            model_name='externalintegration',
            name='connected_org_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='externalintegration',
            name='connected_user_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='externalintegration',
            name='connection_status',
            field=models.CharField(choices=[('connected', 'Connected'), ('syncing', 'Syncing'), ('failed', 'Failed'), ('auth_expired', 'Authentication expired'), ('disconnected', 'Disconnected')], db_index=True, default='connected', max_length=32),
        ),
        migrations.AddField(
            model_name='externalintegration',
            name='encrypted_credentials',
            field=models.TextField(blank=True, default='', help_text='Fernet-sealed credential blob (preferred over plaintext JSON).'),
        ),
        migrations.AddField(
            model_name='externalintegration',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalintegration',
            name='objects_enabled',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. {users: true, deals: true, accounts: false, products: false}'),
        ),
        migrations.AddField(
            model_name='externalintegration',
            name='sync_frequency',
            field=models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='externalintegration',
            name='sync_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Trigger and import rules for deals/orders.'),
        ),
        migrations.AddField(
            model_name='externalintegration',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalintegration',
            name='provider',
            field=models.CharField(choices=[('salesforce', 'Salesforce'), ('generic_rest', 'Generic REST API'), ('webhook', 'Webhook / Zapier'), ('hubspot', 'HubSpot (REST)'), ('zoho', 'Zoho CRM'), ('dynamics', 'Microsoft Dynamics (coming soon)')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='CRMSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=list)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='commissions.externalintegration')),
                ('sync_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_jobs', to='commissions.integrationsynclog')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_sync_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object', models.CharField(db_index=True, max_length=64)),
                ('source_field', models.CharField(max_length=128)),
                ('target_field', models.CharField(max_length=128)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='commissions.externalintegration')),
            ],
            options={
                'ordering': ['source_object', 'target_field'],
                'unique_together': {('connection', 'source_object', 'target_field')},
            },
        ),
        migrations.CreateModel(
            name='CRMIdentityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_provider', models.CharField(db_index=True, max_length=32)),
                ('crm_user_id', models.CharField(db_index=True, max_length=128)),
                ('employee_id', models.CharField(db_index=True, max_length=64)),
                ('employee_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_mappings', to='commissions.externalintegration')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_identity_mappings', to='commissions.organization')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_identity_links', to='commissions.userprofile')),
            ],
            options={
                'ordering': ['crm_provider', 'crm_user_id'],
                'unique_together': {('organization', 'crm_provider', 'crm_user_id')},
            },
        ),
    ]
