# Generated by Django 6.0.5 on 2026-07-23 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0056_auth_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='business_unit',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='changed_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='device',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='module',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='role',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='search_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(blank=True, choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical'), ('success', 'Success')], db_index=True, default='info', max_length=16),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='source',
            field=models.CharField(blank=True, choices=[('web', 'Web'), ('api', 'API'), ('csv_import', 'CSV Import'), ('crm_sync', 'CRM Sync'), ('background_job', 'Background Job')], db_index=True, default='web', max_length=32),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='success', max_length=16),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', '-created_at'], name='audit_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'module', '-created_at'], name='audit_org_module_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'severity', '-created_at'], name='audit_org_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'action'], name='audit_org_action_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'entity_type', 'entity_id'], name='audit_org_entity_idx'),
        ),
    ]
