# Generated by Django 6.0.5 on 2026-07-24 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0057_audit_activity_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('report_type', models.CharField(choices=[('commissions', 'Commission Records'), ('orders', 'Orders'), ('employees', 'Employees'), ('plans', 'Compensation Plans'), ('payouts', 'Payouts'), ('quotas', 'Quotas'), ('audit_logs', 'Audit Logs')], db_index=True, default='commissions', max_length=32)),
                ('visualization', models.CharField(choices=[('table', 'Table'), ('bar', 'Bar chart'), ('line', 'Line chart'), ('pie', 'Pie chart')], default='table', max_length=16)),
                ('group_by', models.CharField(blank=True, default='', max_length=64)),
                ('sort_by', models.CharField(blank=True, default='', max_length=64)),
                ('sort_dir', models.CharField(default='desc', max_length=4)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('organization', 'Organization'), ('role', 'Role-restricted')], default='private', max_length=16)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='commissions.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('aggregation', models.CharField(blank=True, default='', max_length=16)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='commissions.report')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=64)),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('ne', 'Not equals'), ('contains', 'Contains'), ('gte', 'Greater or equal'), ('lte', 'Less or equal'), ('in', 'In list'), ('between', 'Between')], default='eq', max_length=16)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='commissions.report')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=16)),
                ('delivery', models.CharField(choices=[('email_pdf', 'Email PDF'), ('email_excel', 'Email Excel'), ('download', 'Download')], default='email_excel', max_length=16)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('timezone_name', models.CharField(blank=True, default='UTC', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_schedules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='commissions.organization')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='commissions.report')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['organization', '-updated_at'], name='commissions_organiz_2d3f40_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['organization', 'report_type'], name='commissions_organiz_3932e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportfield',
            unique_together={('report', 'field_key')},
        ),
    ]
