# Generated by Django 6.0.5 on 2026-07-24 04:47
#
# Idempotent on Postgres: concurrent Render deploys can leave the composite type
# / table behind while django_migrations never records 0060. A plain CreateModel
# then fails with:
#   UniqueViolation: pg_type_typname_nsp_index
#   Key (typname)=(commissions_compensationdocument) already exists

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _table_names(schema_editor):
    with schema_editor.connection.cursor() as cursor:
        return set(schema_editor.connection.introspection.table_names(cursor))


def _table_exists(schema_editor, table):
    return table in _table_names(schema_editor)


def _column_exists(schema_editor, table, column):
    if not _table_exists(schema_editor, table):
        return False
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(
            cursor, table
        )
    return any(getattr(col, "name", None) == column for col in description)


def _constraint_names(schema_editor, table):
    if not _table_exists(schema_editor, table):
        return {}
    with schema_editor.connection.cursor() as cursor:
        return schema_editor.connection.introspection.get_constraints(cursor, table)


def _index_exists(schema_editor, table, index_name):
    constraints = _constraint_names(schema_editor, table)
    meta = constraints.get(index_name)
    return bool(meta and meta.get("index"))


def _unique_together_exists(schema_editor, table, columns):
    wanted = set(columns)
    for meta in _constraint_names(schema_editor, table).values():
        if meta.get("unique") and set(meta.get("columns") or []) == wanted:
            return True
    return False


def _drop_orphan_composite_type(schema_editor, type_name):
    """Remove a leftover Postgres composite type when the table is gone."""
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM pg_type t
            JOIN pg_namespace n ON n.oid = t.typnamespace
            WHERE n.nspname = current_schema()
              AND t.typname = %s
            """,
            [type_name],
        )
        if cursor.fetchone() is None:
            return
        cursor.execute(f'DROP TYPE IF EXISTS "{type_name}" CASCADE')


class CreateModelIfMissing(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        table = model._meta.db_table
        if _table_exists(schema_editor, table):
            return
        _drop_orphan_composite_type(schema_editor, table)
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.name)
        table = model._meta.db_table
        if not _table_exists(schema_editor, table):
            return
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class AddFieldIfMissing(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        field = to_model._meta.get_field(self.name)
        column = field.column
        if _column_exists(schema_editor, to_model._meta.db_table, column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        from_model = from_state.apps.get_model(app_label, self.model_name)
        field = from_model._meta.get_field(self.name)
        if not _column_exists(schema_editor, from_model._meta.db_table, field.column):
            return
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class AddIndexIfMissing(migrations.AddIndex):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        if _index_exists(schema_editor, model._meta.db_table, self.index.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        if not _index_exists(schema_editor, model._meta.db_table, self.index.name):
            return
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class AlterUniqueTogetherIfMissing(migrations.AlterUniqueTogether):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.name)
        table = to_model._meta.db_table
        unique_together = self.unique_together
        if isinstance(unique_together, set):
            sets = list(unique_together)
        else:
            sets = list(unique_together or [])

        def _columns_for(fields):
            cols = []
            for field_name in fields:
                cols.append(to_model._meta.get_field(field_name).column)
            return cols

        if sets and all(
            _unique_together_exists(schema_editor, table, _columns_for(columns))
            for columns in sets
        ):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0059_userprofile_account_preferences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateModelIfMissing(
            name="CompensationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("compensation_plan", "Compensation Plan"),
                            ("commission_policy", "Commission Policy"),
                            ("quota_letter", "Quota Letter"),
                            ("employee_agreement", "Employee Agreement"),
                            ("approval_document", "Approval Document"),
                            ("exception_approval", "Exception Approval"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("approval_required", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensation_documents",
                        to="commissions.organization",
                    ),
                ),
                (
                    "related_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="commissions.compensationplan",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_compensation_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        AddFieldIfMissing(
            model_name="commission",
            name="supporting_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Policy / plan document referenced for this calculation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commission_references",
                to="commissions.compensationdocument",
            ),
        ),
        CreateModelIfMissing(
            name="CompensationDocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField(default=1)),
                (
                    "version_label",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "file",
                    models.FileField(blank=True, upload_to="compensation_docs/%Y/%m/"),
                ),
                (
                    "storage_backend",
                    models.CharField(blank=True, default="local", max_length=32),
                ),
                (
                    "storage_key",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "file_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("not_required", "Not required"),
                        ],
                        db_index=True,
                        default="not_required",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_to_approve",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="commissions.compensationdocument",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_document_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number", "-created_at"],
            },
        ),
        AddFieldIfMissing(
            model_name="compensationdocument",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="commissions.compensationdocumentversion",
            ),
        ),
        AddFieldIfMissing(
            model_name="commission",
            name="supporting_document_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commission_references",
                to="commissions.compensationdocumentversion",
            ),
        ),
        AddIndexIfMissing(
            model_name="compensationdocumentversion",
            index=models.Index(
                fields=["document", "-version_number"],
                name="compdocver_doc_ver_idx",
            ),
        ),
        AlterUniqueTogetherIfMissing(
            name="compensationdocumentversion",
            unique_together={("document", "version_number")},
        ),
        AddIndexIfMissing(
            model_name="compensationdocument",
            index=models.Index(
                fields=["organization", "status", "-updated_at"],
                name="compdoc_org_status_upd_idx",
            ),
        ),
        AddIndexIfMissing(
            model_name="compensationdocument",
            index=models.Index(
                fields=["organization", "document_type"],
                name="compdoc_org_type_idx",
            ),
        ),
        AddIndexIfMissing(
            model_name="compensationdocument",
            index=models.Index(
                fields=["organization", "related_plan"],
                name="compdoc_org_plan_idx",
            ),
        ),
    ]
