# Generated by Django 6.0.5 on 2026-07-24 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0059_userprofile_account_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('compensation_plan', 'Compensation Plan'), ('commission_policy', 'Commission Policy'), ('quota_letter', 'Quota Letter'), ('employee_agreement', 'Employee Agreement'), ('approval_document', 'Approval Document'), ('exception_approval', 'Exception Approval'), ('other', 'Other')], db_index=True, default='other', max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('approval_required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_documents', to='commissions.organization')),
                ('related_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='commissions.compensationplan')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_compensation_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='commission',
            name='supporting_document',
            field=models.ForeignKey(blank=True, help_text='Policy / plan document referenced for this calculation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_references', to='commissions.compensationdocument'),
        ),
        migrations.CreateModel(
            name='CompensationDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('version_label', models.CharField(blank=True, default='', max_length=32)),
                ('file', models.FileField(blank=True, upload_to='compensation_docs/%Y/%m/')),
                ('storage_backend', models.CharField(blank=True, default='local', max_length=32)),
                ('storage_key', models.CharField(blank=True, default='', max_length=512)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('not_required', 'Not required')], db_index=True, default='not_required', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_to_approve', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='commissions.compensationdocument')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='compensationdocument',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='commissions.compensationdocumentversion'),
        ),
        migrations.AddField(
            model_name='commission',
            name='supporting_document_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_references', to='commissions.compensationdocumentversion'),
        ),
        migrations.AddIndex(
            model_name='compensationdocumentversion',
            index=models.Index(fields=['document', '-version_number'], name='compdocver_doc_ver_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compensationdocumentversion',
            unique_together={('document', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='compensationdocument',
            index=models.Index(fields=['organization', 'status', '-updated_at'], name='compdoc_org_status_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationdocument',
            index=models.Index(fields=['organization', 'document_type'], name='compdoc_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationdocument',
            index=models.Index(fields=['organization', 'related_plan'], name='compdoc_org_plan_idx'),
        ),
    ]
