# Generated by Django 6.0.5 on 2026-07-25 03:47
#
# Idempotent on Postgres: a prior deploy can leave columns / tables behind while
# django_migrations never records 0064 (or a concurrent migrate partially
# applied). Plain AddField then fails with:
#   ProgrammingError: column "calculation_trace" of relation
#   "commissions_commission" already exists

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _table_names(schema_editor):
    with schema_editor.connection.cursor() as cursor:
        return set(schema_editor.connection.introspection.table_names(cursor))


def _table_exists(schema_editor, table):
    return table in _table_names(schema_editor)


def _column_exists(schema_editor, table, column):
    if not _table_exists(schema_editor, table):
        return False
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(
            cursor, table
        )
    return any(getattr(col, "name", None) == column for col in description)


def _constraint_names(schema_editor, table):
    if not _table_exists(schema_editor, table):
        return {}
    with schema_editor.connection.cursor() as cursor:
        return schema_editor.connection.introspection.get_constraints(cursor, table)


def _index_exists(schema_editor, table, index_name):
    constraints = _constraint_names(schema_editor, table)
    meta = constraints.get(index_name)
    return bool(meta and meta.get("index"))


def _drop_orphan_composite_type(schema_editor, type_name):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM pg_type t
            JOIN pg_namespace n ON n.oid = t.typnamespace
            WHERE n.nspname = current_schema()
              AND t.typname = %s
            """,
            [type_name],
        )
        if cursor.fetchone() is None:
            return
        cursor.execute(f'DROP TYPE IF EXISTS "{type_name}" CASCADE')


class CreateModelIfMissing(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        table = model._meta.db_table
        if _table_exists(schema_editor, table):
            return
        _drop_orphan_composite_type(schema_editor, table)
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.name)
        table = model._meta.db_table
        if not _table_exists(schema_editor, table):
            return
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class AddFieldIfMissing(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        field = to_model._meta.get_field(self.name)
        column = field.column
        if _column_exists(schema_editor, to_model._meta.db_table, column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        from_model = from_state.apps.get_model(app_label, self.model_name)
        field = from_model._meta.get_field(self.name)
        if not _column_exists(schema_editor, from_model._meta.db_table, field.column):
            return
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class AddIndexIfMissing(migrations.AddIndex):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        if _index_exists(schema_editor, model._meta.db_table, self.index.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        if not _index_exists(schema_editor, model._meta.db_table, self.index.name):
            return
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0063_governance_compliance_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commissionrule",
            options={"ordering": ["priority", "sequence", "id"]},
        ),
        AddFieldIfMissing(
            model_name="commission",
            name="calculation_trace",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Resolved plan / version / rule / override chain for this payout.",
            ),
        ),
        AddFieldIfMissing(
            model_name="commission",
            name="override_used",
            field=models.BooleanField(db_index=True, default=False),
        ),
        AddFieldIfMissing(
            model_name="commissionrule",
            name="condition_logic",
            field=models.CharField(
                choices=[
                    ("and", "Match all conditions (AND)"),
                    ("or", "Match any condition (OR)"),
                ],
                default="and",
                max_length=8,
            ),
        ),
        AddFieldIfMissing(
            model_name="commissionrule",
            name="priority",
            field=models.PositiveIntegerField(
                db_index=True,
                default=5,
                help_text="Lower runs first. 1 is reserved for employee overrides.",
            ),
        ),
        AddFieldIfMissing(
            model_name="commissionrule",
            name="scope",
            field=models.CharField(
                choices=[
                    ("territory", "Territory Rule"),
                    ("business_unit", "Business Unit Rule"),
                    ("role", "Role Rule"),
                    ("plan_default", "Compensation Plan Default"),
                ],
                db_index=True,
                default="plan_default",
                help_text="Hierarchy level this rule represents.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="commissionrulecondition",
            name="field",
            field=models.CharField(
                choices=[
                    ("region", "Region"),
                    ("product_name", "Product"),
                    ("product_category", "Product Category"),
                    ("service_name", "Service"),
                    ("distribution", "Distribution"),
                    ("customer_segment", "Customer Segment"),
                    ("customer_type", "Customer Type"),
                    ("business_group", "Business Unit"),
                    ("department", "Department"),
                    ("order_status", "Order Status"),
                    ("currency", "Currency"),
                    ("position_name", "Position Name"),
                    ("employee_id", "Employee ID"),
                    ("sales_amount", "Sales Amount"),
                    ("revenue", "Revenue"),
                    ("margin", "Margin"),
                    ("achievement_pct", "Achievement %"),
                    ("quota_pct", "Quota %"),
                    ("territory_code", "Territory Code"),
                    ("territory", "Territory"),
                    ("role", "Role"),
                    ("sales_channel", "Sales Channel"),
                    ("order_date", "Order Date"),
                    ("plan_basis", "Plan Basis"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="commissionrulecondition",
            name="operator",
            field=models.CharField(
                choices=[
                    ("eq", "Equals"),
                    ("neq", "Not equals"),
                    ("in", "In list"),
                    ("contains", "Contains"),
                    ("gt", "Greater than"),
                    ("gte", "Greater or equal"),
                    ("lt", "Less than"),
                    ("lte", "Less or equal"),
                    ("between", "Between (comma separated)"),
                    ("empty", "Is empty"),
                    ("not_empty", "Is not empty"),
                ],
                default="eq",
                max_length=20,
            ),
        ),
        CreateModelIfMissing(
            name="EmployeeCompensationOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "override_type",
                    models.CharField(
                        choices=[
                            ("commission_rate", "Commission Rate"),
                            ("bonus", "Bonus"),
                            ("accelerator", "Accelerator"),
                            ("multiplier", "Multiplier"),
                            ("quota", "Quota"),
                            ("eligibility", "Eligibility"),
                            ("draw", "Draw"),
                            ("recovery", "Recovery"),
                        ],
                        db_index=True,
                        default="commission_rate",
                        max_length=32,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "value_unit",
                    models.CharField(
                        choices=[
                            ("percent", "Percent"),
                            ("currency", "Currency"),
                            ("multiplier", "Multiplier"),
                            ("units", "Units"),
                            ("boolean", "Yes / No"),
                        ],
                        default="percent",
                        max_length=20,
                    ),
                ),
                (
                    "previous_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Plan value replaced by this override, captured at creation.",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("effective_from", models.DateField(db_index=True)),
                (
                    "effective_to",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("priority", models.PositiveIntegerField(default=1)),
                (
                    "stop_on_match",
                    models.BooleanField(
                        default=True,
                        help_text="Skip plan rules of the same type once this override applies.",
                    ),
                ),
                ("approval_required", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compensation_overrides_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compensation_overrides_to_approve",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compensation_plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Plan this override modifies. Blank means the employee's assigned plan.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_overrides",
                        to="commissions.compensationplan",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compensation_overrides_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensation_overrides",
                        to="commissions.userprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensation_overrides",
                        to="commissions.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "-effective_from", "-id"],
            },
        ),
        AddFieldIfMissing(
            model_name="commission",
            name="applied_override",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee override that superseded the plan rules, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commissions",
                to="commissions.employeecompensationoverride",
            ),
        ),
        CreateModelIfMissing(
            name="EmployeeCompensationOverrideEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "override_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("created", "Override Created"),
                            ("updated", "Override Updated"),
                            ("submitted", "Submitted For Approval"),
                            ("approved", "Override Approved"),
                            ("rejected", "Override Rejected"),
                            ("expired", "Override Expired"),
                            ("removed", "Override Removed"),
                            ("applied", "Override Applied To Commission"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("old_value", models.JSONField(blank=True, default=dict)),
                ("new_value", models.JSONField(blank=True, default=dict)),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                (
                    "status_after",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compensation_override_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "override",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="commissions.employeecompensationoverride",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        AddIndexIfMissing(
            model_name="employeecompensationoverride",
            index=models.Index(
                fields=["employee", "status", "effective_from"],
                name="empoverride_emp_status_idx",
            ),
        ),
        AddIndexIfMissing(
            model_name="employeecompensationoverride",
            index=models.Index(
                fields=["organization", "override_type", "status"],
                name="empoverride_org_type_idx",
            ),
        ),
    ]
