# Generated by Django 6.0.5 on 2026-07-25 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0063_governance_compliance_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionrule',
            options={'ordering': ['priority', 'sequence', 'id']},
        ),
        migrations.AddField(
            model_name='commission',
            name='calculation_trace',
            field=models.JSONField(blank=True, default=dict, help_text='Resolved plan / version / rule / override chain for this payout.'),
        ),
        migrations.AddField(
            model_name='commission',
            name='override_used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='condition_logic',
            field=models.CharField(choices=[('and', 'Match all conditions (AND)'), ('or', 'Match any condition (OR)')], default='and', max_length=8),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=5, help_text='Lower runs first. 1 is reserved for employee overrides.'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='scope',
            field=models.CharField(choices=[('territory', 'Territory Rule'), ('business_unit', 'Business Unit Rule'), ('role', 'Role Rule'), ('plan_default', 'Compensation Plan Default')], db_index=True, default='plan_default', help_text='Hierarchy level this rule represents.', max_length=32),
        ),
        migrations.AlterField(
            model_name='commissionrulecondition',
            name='field',
            field=models.CharField(choices=[('region', 'Region'), ('product_name', 'Product'), ('product_category', 'Product Category'), ('service_name', 'Service'), ('distribution', 'Distribution'), ('customer_segment', 'Customer Segment'), ('customer_type', 'Customer Type'), ('business_group', 'Business Unit'), ('department', 'Department'), ('order_status', 'Order Status'), ('currency', 'Currency'), ('position_name', 'Position Name'), ('employee_id', 'Employee ID'), ('sales_amount', 'Sales Amount'), ('revenue', 'Revenue'), ('margin', 'Margin'), ('achievement_pct', 'Achievement %'), ('quota_pct', 'Quota %'), ('territory_code', 'Territory Code'), ('territory', 'Territory'), ('role', 'Role'), ('sales_channel', 'Sales Channel'), ('order_date', 'Order Date'), ('plan_basis', 'Plan Basis')], max_length=50),
        ),
        migrations.AlterField(
            model_name='commissionrulecondition',
            name='operator',
            field=models.CharField(choices=[('eq', 'Equals'), ('neq', 'Not equals'), ('in', 'In list'), ('contains', 'Contains'), ('gt', 'Greater than'), ('gte', 'Greater or equal'), ('lt', 'Less than'), ('lte', 'Less or equal'), ('between', 'Between (comma separated)'), ('empty', 'Is empty'), ('not_empty', 'Is not empty')], default='eq', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeCompensationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('override_type', models.CharField(choices=[('commission_rate', 'Commission Rate'), ('bonus', 'Bonus'), ('accelerator', 'Accelerator'), ('multiplier', 'Multiplier'), ('quota', 'Quota'), ('eligibility', 'Eligibility'), ('draw', 'Draw'), ('recovery', 'Recovery')], db_index=True, default='commission_rate', max_length=32)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('value_unit', models.CharField(choices=[('percent', 'Percent'), ('currency', 'Currency'), ('multiplier', 'Multiplier'), ('units', 'Units'), ('boolean', 'Yes / No')], default='percent', max_length=20)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=4, help_text='Plan value replaced by this override, captured at creation.', max_digits=15, null=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('priority', models.PositiveIntegerField(default=1)),
                ('stop_on_match', models.BooleanField(default=True, help_text='Skip plan rules of the same type once this override applies.')),
                ('approval_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_overrides_approved', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_overrides_to_approve', to=settings.AUTH_USER_MODEL)),
                ('compensation_plan', models.ForeignKey(blank=True, help_text="Plan this override modifies. Blank means the employee's assigned plan.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_overrides', to='commissions.compensationplan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_overrides_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_overrides', to='commissions.userprofile')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensation_overrides', to='commissions.organization')),
            ],
            options={
                'ordering': ['priority', '-effective_from', '-id'],
            },
        ),
        migrations.AddField(
            model_name='commission',
            name='applied_override',
            field=models.ForeignKey(blank=True, help_text='Employee override that superseded the plan rules, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='commissions.employeecompensationoverride'),
        ),
        migrations.CreateModel(
            name='EmployeeCompensationOverrideEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_name', models.CharField(blank=True, default='', max_length=255)),
                ('event', models.CharField(choices=[('created', 'Override Created'), ('updated', 'Override Updated'), ('submitted', 'Submitted For Approval'), ('approved', 'Override Approved'), ('rejected', 'Override Rejected'), ('expired', 'Override Expired'), ('removed', 'Override Removed'), ('applied', 'Override Applied To Commission')], db_index=True, max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('status_after', models.CharField(blank=True, default='', max_length=20)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_override_events', to=settings.AUTH_USER_MODEL)),
                ('override', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='commissions.employeecompensationoverride')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='employeecompensationoverride',
            index=models.Index(fields=['employee', 'status', 'effective_from'], name='empoverride_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecompensationoverride',
            index=models.Index(fields=['organization', 'override_type', 'status'], name='empoverride_org_type_idx'),
        ),
    ]
