# Generated by Django 6.0.5 on 2026-07-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0065_employee_commission_rule_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrule',
            name='apply_to_all_plan_participants',
            field=models.BooleanField(db_index=True, default=False, help_text="When true, this rule applies to every employee who belongs to the rule's compensation plan (current and future). Individual assignments are not required."),
        ),
    ]
