# Generated by Django 6.0.5 on 2026-05-16 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('effective_start_date', models.DateField(auto_now_add=True)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='commissions.userprofile')),
                ('parent_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='commissions.userprofile')),
            ],
            options={
                'unique_together': {('parent_participant', 'child_participant')},
            },
        ),
    ]
