# Generated by Django 6.0.5 on 2026-05-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_userprofile_name_userprofile_position_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
