# Generated by Django 6.0.5 on 2026-05-17 04:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_alter_userprofile_position_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensationplan',
            name='bonus_amount',
        ),
        migrations.RemoveField(
            model_name='compensationplan',
            name='commission_percent',
        ),
        migrations.RemoveField(
            model_name='compensationplan',
            name='max_sales',
        ),
        migrations.RemoveField(
            model_name='compensationplan',
            name='min_sales',
        ),
        migrations.AddField(
            model_name='compensationplan',
            name='basis_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='compensationplan',
            name='business_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compensationplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compensationplan',
            name='effective_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compensationplan',
            name='effective_start_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compensationplan',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compensationplan',
            name='market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compensationplan',
            name='pay_period_type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annual', 'Annual')], default='Monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='compensationplan',
            name='plan_basis',
            field=models.CharField(choices=[('Product', 'Product'), ('Service', 'Service'), ('Individual', 'Individual'), ('Role', 'Role'), ('Region', 'Region'), ('Customer Segment', 'Customer Segment')], default='Individual', max_length=50),
        ),
        migrations.AddField(
            model_name='compensationplan',
            name='position_name',
            field=models.CharField(blank=True, help_text='Unique position name used during commission calculations', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='compensationplan',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compensationplan',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='compensationplan',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compensationplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='compensationplan',
            name='plan_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='CompensationTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('min_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_sales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='commissions.compensationplan')),
            ],
            options={
                'ordering': ['min_sales'],
            },
        ),
    ]
