# Generated by Django 6.0.5 on 2026-05-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0007_remove_compensationplan_bonus_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('order_date', models.DateField()),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('position_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('service_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('order_status', models.CharField(default='Booked', max_length=50)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
