# Generated by Django 6.0.5 on 2026-05-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
