# Generated by Django 6.0.5 on 2026-05-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0016_compensationplan_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensationplan',
            name='is_default',
        ),
    ]
