# Generated by Django 6.0.5 on 2026-05-30 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0018_sale_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commission',
            name='calculated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='compensation_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='commissions.compensationplan'),
        ),
        migrations.AddField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('calculated', 'Calculated'), ('approved', 'Approved')], db_index=True, default='calculated', max_length=20),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['status', 'calculated_at'], name='commissions_status_b4d7f6_idx'),
        ),
    ]
