# Generated by Django 6.0.5 on 2026-05-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0021_phase4_organization_importjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
